#!/bin/bash
IGNORED_TABLES_STRING=''
while IFS= read -r line; do
    [ ! -z "${line// }" ] && IGNORED_TABLES_STRING+=" --ignore-table=$line"
done < .ignore_tables
mysqldump --defaults-extra-file=.options --all-databases --quick --lock-tables=false --single-transaction --max-allowed-packet=1024M $IGNORED_TABLES_STRING

